# description
name: "boilerplate-assets"
description: "Assets for quick start with web project."
keywords: "code, boilerplate, assets, css, oacss"
author: "Leszek Pietrzak"

# address settings
baseurl: "http://boilerplate-assets.smutnyleszek.com"
sourceurl: "https://github.com/smutnyleszek/boilerplate-assets"
imagesPath: "/dist/images/"

# urls
googleFontsCode: family=Source+Sans+Pro:400,700,400italic,700italic&subset=latin,latin-ext

# site configuration
safe: true
quiet: false
future: true
encoding: utf-8
markdown: kramdown
kramdown:
    auto_ids: false
timezone: Europe/Warsaw

# excludes
exclude:
    - src
    - node_modules
    - LICENSE
    - README.md
    - package.json
